---
spine1-nxos:
  #hostname: 172.29.151.1
  hostname: nebula.packetflow.co.uk
  port: 9001
  groups:
    - nxos
spine2-nxos:
  #hostname: 172.29.151.2
  hostname: nebula.packetflow.co.uk
  port: 9002
  groups:
    - nxos
leaf1-ios:
  #hostname: 172.29.151.3
  hostname: nebula.packetflow.co.uk
  port: 9003
  groups:
    - iosxe
leaf2-ios:
  #hostname: 172.29.151.4
  hostname: nebula.packetflow.co.uk
  port: 9004
  groups:
    - iosxe
leaf3-junos:
  #hostname: 172.29.151.5
  hostname: nebula.packetflow.co.uk
  port: 9005
  groups:
    - junos
leaf4-junos:
  #hostname: 172.29.151.6
  hostname: nebula.packetflow.co.uk
  port: 9006
  groups:
    - junos
leaf5-eos:
  #hostname: 172.29.151.7
  hostname: nebula.packetflow.co.uk
  port: 9007
  groups:
    - eos
leaf6-eos:
  #hostname: 172.29.151.8
  hostname: nebula.packetflow.co.uk
  port: 9008
  groups:
    - eos